#!/bin/bash
### BEGIN INIT INFO                                                                                                                                       
# Provides: torrentor
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: manage torrentor stack.
# Description:
### END INIT INFO
case "$1" in  
  start)
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    sudo screen -S torrentor  -d -m ./core.py 
    echo "setting up welcome screen"
    ;; 
  restart)
    echo "kill previous processes"
    sudo kill `pgrep -f redis-server`
    sudo kill `pgrep -f rtorrent`
    sudo kill `pgrep -f core.py`
    sudo kill `pgrep -f feh`
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    sudo screen -S torrentor  -d -m ./core.py 
    echo "setting up welcome screen"
    ;; 
  stop)
    echo "kill previous processes"
    sudo kill `pgrep -f redis-server`
    sudo kill `pgrep -f rtorrent`
    sudo kill `pgrep -f core.py`
    sudo kill `pgrep -f feh`
    ;;

  *)
  echo "Usage: $0 start|restart|stop" >&2
  exit 3
  ;;
esac
