#!/bin/bash
### BEGIN INIT INFO                                                                                                                                       
# Provides: torrentor
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: Execute the reboot command.
# Description:
### END INIT INFO
case "$1" in  
  start)
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    sudo screen -S torrentor  -d -m ./core.py 
    ;; 
  restart|reload|force-reload)
    echo "kill previous processes"
    sudo kill `pgrep -f redis-server`
    sudo kill `pgrep -f rtorrent`
    sudo kill `pgrep -f core.py`
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    sudo screen -S torrentor  -d -m ./core.py 
    ;; 
  stop)
    echo "kill previous processes"
    ps ax | grep redis-server | cut -c 1-5 | sudo xargs kill
    ps ax | grep rtorrent | cut -c 1-5 | sudo xargs kill
    ps ax | grep core.py | cut -c 1-5 | sudo xargs kill
    ;;

  *)
  echo "Usage: $0 start|stop" >&2
  exit 3
  ;;
esac
