#!/bin/bash
### BEGIN INIT INFO                                                                                                                                       
# Provides: torrentor
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: Execute the reboot command.
# Description:
### END INIT INFO
case "$1" in  
  start)
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    sudo screen -S torrentor  -d -m ./core.py 
    echo "setting up welcome screen"
    xset -display :0 s reset
    DISPLAY=:0 feh -F -X --hide-pointer -x -q --draw-tinted --info "python <SITE_DIR>/ip.py" -C /usr/share/fonts/truetype/ttf-dejavu/ -e DejaVuSans/36 -Z -D 5 -B black <SITE_DIR>/screen.png &

    ;; 
  restart|reload|force-reload)
    echo "kill previous processes"
    sudo kill `pgrep -f redis-server`
    sudo kill `pgrep -f rtorrent`
    sudo kill `pgrep -f core.py`
    sudo kill `pgrep -f feh`
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    sudo screen -S torrentor  -d -m ./core.py 
    echo "setting up welcome screen"
    xset -display :0 s reset
    DISPLAY=:0 feh -F -X --hide-pointer -x -q --draw-tinted --info "python <SITE_DIR>/ip.py" -C /usr/share/fonts/truetype/ttf-dejavu/ -e DejaVuSans/36 -Z -D 5 -B black <SITE_DIR>/screen.png &
    ;; 
  stop)
    echo "kill previous processes"
    sudo kill `pgrep -f redis-server`
    sudo kill `pgrep -f rtorrent`
    sudo kill `pgrep -f core.py`
    sudo kill `pgrep -f feh`
    ;;

  *)
  echo "Usage: $0 start|stop" >&2
  exit 3
  ;;
esac
