#!/bin/bash
### BEGIN INIT INFO                                                                                                                                       
# Provides: torrentor
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: manage torrentor stack.
# Description:
### END INIT INFO
case "$1" in  
  start)
    u="<USER>"
    echo "attaching on user: $u"
    echo "running redis"
    sudo su - "$u" -c "screen -dmS redis redis-server"
    echo "running rtorrent"
    sudo su - "$u" -c "screen -dmS rtorrent rtorrent"
    echo "running web layer"
    sudo su - "$u" -c "spawn-fcgi -f <SITE_DIR>/core.py -a 127.0.0.1 -p 8092"
    ;; 
  stop)
    echo "killing redis"
    ps ax | grep redis-server | cut -c 1-5 | sudo xargs kill
    echo "killing rtorrent"
    ps ax | grep rtorrent | cut -c 1-5 | sudo xargs kill
    rm -rf "<SITE_DIR>/session/*"
    echo "killing weblayer"
    ps ax | grep core.py | cut -c 1-5 | sudo xargs kill
    ps ax | grep feh | cut -c 1-5 | sudo xargs kill
    ;;
  *)
  echo "Usage: $0 start|stop" >&2
  exit 3
  ;;
esac
