#!/bin/bash
### BEGIN INIT INFO                                                                                                                                       
# Provides: torrentor
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: manage torrentor stack.
# Description:
### END INIT INFO
case "$1" in  
  start)
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    spawn-fcgi -f <SITE_DIR>/core.py -a 127.0.0.1 -p 8092
    ;; 
  restart)
    echo "kill previous processes"
    ps ax | grep redis-server | cut -c 1-5 | sudo xargs kill
    ps ax | grep rtorrent | cut -c 1-5 | sudo xargs kill
    ps ax | grep core.py | cut -c 1-5 | sudo xargs kill
    ps ax | grep feh | cut -c 1-5 | sudo xargs kill
    echo "running redis"
    screen -S redis  -d -m redis-server
    echo "running rtorrent"
    screen -S rtorrent  -d -m rtorrent
    echo "running web layer"
    spawn-fcgi -f <SITE_DIR>/core.py -a 127.0.0.1 -p 8092
    ;; 
  stop)
    echo "kill previous processes"
    ps ax | grep redis-server | cut -c 1-5 | sudo xargs kill
    ps ax | grep rtorrent | cut -c 1-5 | sudo xargs kill
    ps ax | grep core.py | cut -c 1-5 | sudo xargs kill
    ps ax | grep feh | cut -c 1-5 | sudo xargs kill
    ;;

  *)
  echo "Usage: $0 start|restart|stop" >&2
  exit 3
  ;;
esac
