#!/usr/bin/env python
# -*- coding utf-8 -*-
from __future__ import with_statement
import os,sys,redis,datetime

def main():
  with open("calliope.log","a") as log:
    file = sys.argv[1]
    log.write('[%s]: File path: %s\n'%(datetime.datetime.now(),file))
    #r = redis.StrictRedis(host='localhost',port=6379,db=0)
    #r.delete('/')
    log.write('[%s]: Removed: cache on path "/".\n\n'%datetime.datetime.now())
  
if __name__=='__main__': main()
